myapp/app/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('', views.IndexMain.as_view())
]

myapp/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path(패턴, 매핑) /blog/
    # 글 목록 조회
    path("", views.Index.as_view(), name='list'),
    # 글 상세 조회
    path("detail/<int:pk>/", views.DetailView.as_view(), name='detail'),
    # 글 작성
    path("write/", views.Write.as_view(), name='write'),
    # 글 수정
    path("detail/<int:pk>/edit/", views.Update.as_view(), name='edit'),
    # 글 삭제
    path("detail/<int:pk>/delete/", views.Delete.as_view(), name='delete'),
    # 코멘트 작성
    path("detail/<int:pk>/comment/write/", views.CommentWrite.as_view(), name='cm-write'),
    # 코멘트 삭제
    path("detail/comment/<int:pk>/delete/", views.CommentDelete.as_view(), name='cm-delete'),
    # 태그 작성
    path("detail/<int:pk>/hashtag/write/", views.HashTagWrite.as_view(), name='tag-write'),
    # 태그 삭제
    path("detail/<int:pk>/hashtag/delete/", views.HashTagDelete.as_view(), name='tag-delete'),
]

myapp/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    content = models.TextField(max_length=500)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.content


class HashTag(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    name = models.CharField(max_length=10)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

myapp/blog/forms.py
# blog/forms.py
from django import forms
from .models import Post, Comment, HashTag

# Form: html에 있는 form 태그
# Model Form: model을 사용하는 form
class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ['title', 'content']


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'rows': '3', 'cols':'35'})
        }


class HashTagForm(forms.ModelForm):
    
    class Meta:
        model = HashTag
        fields = ['name']

myapp/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from .models import Post, Comment, HashTag
from .forms import PostForm, CommentForm, HashTagForm


### Post
class Index(View):
    
    def get(self, request):
        posts = Post.objects.all()
        context = {
            "posts": posts,
            "title": "Blog"
        }
        return render(request, 'blog/post_list.html', context)


class Write(LoginRequiredMixin, View):
    
    def get(self, request):
        form = PostForm()
        context = {
            'form': form,
            "title": "Blog"
        }
        return render(request, 'blog/post_form.html', context)
    
    def post(self, request):
        form = PostForm(request.POST)
        
        if form.is_valid():
            post = form.save(commit=False)
            post.writer = request.user
            post.save()
            return redirect('blog:list')
        
        context = {
            'form': form
        }
        
        return render(request, 'blog/post_form.html', context)


class Update(View):
    
    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        form = PostForm(initial={'title': post.title, 'content': post.content})
        context = {
            'form': form,
            'post': post,
            "title": "Blog"
        }
        return render(request, 'blog/post_edit.html', context)
    
    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        form = PostForm(request.POST)
        
        if form.is_valid():
            post.title = form.cleaned_data['title']
            post.content = form.cleaned_data['content']
            post.save()
            return redirect('blog:detail', pk=pk)
        
        context = {
            'form': form,
            "title": "Blog"
        }
        
        return render(request, 'blog/post_edit.html', context)
        

class Delete(View):
    
    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        post.delete()
        return redirect('blog:list')


class DetailView(View):
    
    def get(self, request, pk):
        post = Post.objects.prefetch_related('comment_set', 'hashtag_set').get(pk=pk)
        
        comments = post.comment_set.all()
        hashtags = post.hashtag_set.all()

        comment_form = CommentForm()
        hashtag_form = HashTagForm()
        
        context = {
            "title": "Blog",
            'post_id': pk,
            'post_title': post.title,
            'post_writer': post.writer,
            'post_content': post.content,
            'post_created_at': post.created_at,
            'comments': comments,
            'hashtags': hashtags,
            'comment_form': comment_form,
            'hashtag_form': hashtag_form,
        }
        
        return render(request, 'blog/post_detail.html', context)


### Comment
class CommentWrite(LoginRequiredMixin, View):

    def post(self, request, pk):
        form = CommentForm(request.POST)
        post = get_object_or_404(Post, pk=pk)

        if form.is_valid():
            content = form.cleaned_data['content']
            writer = request.user

            try:
                comment = Comment.objects.create(post=post, content=content, writer=writer)
            except ObjectDoesNotExist as e:
                print('Post does not exist.', str(e))
            except ValidationError as e:
                print('Valdation error occurred', str(e))
            
            return redirect('blog:detail', pk=pk)
        
        hashtag_form = HashTagForm()
        
        context = {
            "title": "Blog",
            'post_id': pk,
            'comments': post.comment_set.all(),
            'hashtags': post.hashtag_set.all(),
            'comment_form': form,
            'hashtag_form': hashtag_form
        }
        return render(request, 'blog/post_detail.html', context)


class CommentDelete(View):
    
    def post(self, request, pk):
        comment = get_object_or_404(Comment, pk=pk)
        
        post_id = comment.post.id

        comment.delete()
        
        return redirect('blog:detail', pk=post_id)


### Tag
class HashTagWrite(LoginRequiredMixin, View):
    
    def post(self, request, pk):
        form = HashTagForm(request.POST)
        
        post = get_object_or_404(Post, pk=pk)
        
        if form.is_valid():
            name = form.cleaned_data['name']
            writer = request.user

            try:
                hashtag = HashTag.objects.create(post=post, name=name, writer=writer)
            except ObjectDoesNotExist as e:
                print('Post does not exist.', str(e))
            except ValidationError as e:
                print('Valdation error occurred', str(e))

            return redirect('blog:detail', pk=pk)

        comment_form = CommentForm()
        
        context = {
            'title': 'Blog',
            'post': post,
            'comments': post.comment_set.all(),
            'hashtags': post.hashtag_set.all(),
            'comment_form': comment_form,
            'hashtag_form': form
        }
        
        return render(request, 'blog/post_detail.html', context)


class HashTagDelete(View):
    
    def post(self, request, pk):
        hashtag = get_object_or_404(HashTag, pk=pk)
        post_id = hashtag.post.id

        hashtag.delete()
        
        return redirect('blog:detail', pk=post_id)

myapp/blog/templates/blog/Post_edit.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
  {% if form.errors %}
    {% include 'blog/form_error.html' %}
  {% else %}
    {% trans 'Welcome!' %}
    <form action="{% url 'blog:edit' pk=post.pk %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="{% trans 'Edit' %}" />
    </form>
  {% endif %}
{% endblock %}

myapp/blog/templates/blog/form_error.html
<!-- form error 출력 -->

<div class="alert alert-danger">
    {{ form }}
</div>

myapp/blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

    <h2>{% trans 'Title:' %} {{ post_title }}</h2>

    {% if post_writer == request.user %}
        <a href="{% url 'blog:edit' pk=post_id %}" class="btn">{% trans 'Edit' %}</a>
        <form action="{% url 'blog:delete' pk=post_id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="{% trans 'Delete' %}" class="btn">
        </form>
    {% endif %}

    <p>{% trans 'Content:' %} {{ post_content }}</p>
    <p>{% trans 'Writer:' %} {{ post_writer }}</p>
    <p>{% trans 'Date:' %} {{ post_created_at }}</p>
    <hr>

    <!-- 작성 화면 -->
    <h3>댓글</h3>
    <form action="{% url 'blog:cm-write' pk=post_id %}" method="post">
        {% csrf_token %}
        {% if comment_form.errors %}
            {% with form=comment_form %}
                {% include 'blog/form_error.html' %}
            {% endwith %}
        {% else %}
            {{ comment_form.content }}
        {% endif %}
        <input type="submit" value="{% trans 'Submit' %}">
    </form>
    <br>
    
    <!-- comments -->
    {% if comments %}
        <ul>
            {% for comment in comments %}
                <li>{{ comment.content }} / {{ comment.created_at }}
                    {% if comment.writer == request.user %}
                        <form action="{% url 'blog:cm-delete' pk=comment.pk %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="X" class='btn'>
                        </form>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>{% trans 'There is no comment.' %}</p>
    {% endif %}
    <hr>

    <!-- hashtags -->
    <h3>해시태그</h3>
    <form action="{% url 'blog:tag-write' pk=post_id %}" method="post">
        {% csrf_token %}
        {% if hashtag_form.errors %}
            {% with form=hashtag_form %}
                {% include 'blog/form_error.html' %}
            {% endwith %}
        {% else %}
            {{ hashtag_form.name }}
        {% endif %}
        <input type="submit" value="{% trans 'Submit' %}">
    </form>

    {% if hashtags %}
        <ul>
            {% for hashtag in hashtags %}
            <li>
                {{ hashtag }}
                {% if hashtag.writer == request.user %}
                    <form action="{% url 'blog:tag-delete' pk=hashtag.pk %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="X" class='btn'>
                    </form>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <br>
        <p>{% trans 'There is no hashtag.' %}</p>
    {% endif %}

{% endblock %}

myapp/blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <p>블로그 글 작성 화면</p>
    <form action="{% url 'blog:write' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-outline-success" value="{% trans 'Submit' %}">
    </form>
{% endblock %}

myapp/blog/templates/blog/post_list.html
{% extends 'base.html' %} {% block content %}
<p class="main-title">블로그 게시판 첫 화면입니다.</p>
<form action="{% url 'blog:write' %}" method="get">
  <input
    type="hidden"
    name="{{ redirect_field_name }}"
    value="{{ request.GET.next }}"
  />
  <input type="submit" value="글 작성" />
</form>

{% if posts %}
<table class="table table-bordered">
  <thead class="table-light">
    <tr>
      <td>제목</td>
      <td>작성일</td>
      <td>작성자</td>
    </tr>
  </thead>
  <tbody>
    {% for post in posts %}
    <tr>
      <td>
        <a href="{% url 'blog:detail' pk=post.pk %}" class="btn"
          >{{ post.title }}</a
        >
      </td>
      <td>
        <a href="{% url 'blog:detail' pk=post.pk %}" class="btn"
          >{{ post.created_at }}</a
        >
      </td>
      <td>{{ post.writer }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p>작성된 게시물이 없습니다.</p>
{% endif %} {% endblock %}